version: "3"
services:
  mongodb:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - ./mongo-volume:/data/db
  python-ea:
    build: .
    command: python -m solai_evolutionary_algorithm run_with_database
    links:
      - mongodb
  redis:
    image: "redis:alpine"
    command: redis-server
    ports:
      - "6379:6379"
