version: "3"
services:
  py-mongo:
    build:
      context: ${PWD}
    volumes:
      - $PWD/mongo-data:/data/db
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
        - MONGO_INITDB_ROOT_PASSWORD=1234
