version: "3"
services:
  mongodb:
    image: mongo
    ports:
      - "27017:27017"
  python-ea:
    build: .
    command: python -m solai_evolutionary_algorithm run_with_database
    links:
      - mongodb
  redis:
    image: redis
